### ISSUE TITLE
Having Problems Running Script in Blender

### ISSUE THREAD

**Issue by DONNVS** [rwsarmstrong/strongtrack#11]
Hi, whenever I try to run the script in Blender "Python Script Failed, Check The Message in the System Console. When I do I get the messages below:

Traceback (most recent call last):
  File "E:\Projects\Mocap\Blender Project\Strongtrack08BlenderExample.blend\blender_import_strongtrack_data.py", line 7, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\site-packages\numpy\lib\npyio.py", line 968, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\site-packages\numpy\lib\_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\site-packages\numpy\lib\_datasource.py", line 615, in open
    found = self._findfile(path)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\site-packages\numpy\lib\_datasource.py", line 452, in _findfile
    if self.exists(name):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\site-packages\numpy\lib\_datasource.py", line 549, in exists
    if os.path.exists(path):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path
Error: Python script failed, check the message in the system console

I looked at my .txt export file and everything looks like zeros in it. Maybe I am having a problem with my export? I am using the version that runs though Blender. When I run the compiled version it crashes when I try to export the txt file. I attached my exported .txt file to this message to maybe help decode it.

[BlendTestExport2.txt](https://github.com/rwsarmstrong/strongtrack/files/6239643/BlendTestExport2.txt)

**Comment by DONNVS** [comment]
BTW, I am running this in Blender 2.92

**Comment by DONNVS** [comment]
Here is the Cmd window when i run the compiled version of StrongTrack. It crashes everytime I try to export the .txt file.

pausing
XML file loaded successfully
model with values found
Keyposes extraction poses found and loaded
showing points first time
1
Traceback (most recent call last):
  File "strongtrack.py", line 1481, in export
  File "decomp_functions.py", line 267, in findCoeffsAll
  File "decomp_functions.py", line 199, in findCoeffsBrowsSimple
  File "decomp_functions.py", line 149, in simpleBrowUp
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by TashaSkyUp** [comment]
Kinda odd, the error is reporting that a very basic array is not as large as it really should be. Can you detail your whole process for reproducing this error?
